language: cpp
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get install cmake libsfml-dev lcov
  - sudo pip install cpp-coveralls --use-mirrors
script:
  - cmake -DCMAKE_BUILD_TYPE="Debug" .
  - make Aquila aquila_test
  - ctest
after_success:
  - echo $CXX
  - bash -c 'if [[ $CXX == */g++* ]]; then coveralls --exclude examples --exclude lib --exclude tests; fi'
