version: 3.0.0.{build}

init:
  - cmd: cmake --version

before_build:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -G"Visual Studio 12" ..

build_script:
  - cmd: msbuild Aquila.sln /target:Aquila

test_script:
  - cmd: msbuild Aquila.sln /target:tests
